const images = {
    'ข้าวกระเพราไก่.jpg': require('./ข้าวกระเพราไก่.jpg'),
    'ข้าวกะเพราหมู.jpg': require('./ข้าวกะเพราหมู.jpg'),
    'ข้าวผัดไก่.jpg': require('./ข้าวผัดไก่.jpg'),
    'ข้าวผัดหมู.jpg': require('./ข้าวผัดหมู.jpg'),
    'กาแฟ.jpg': require('./กาแฟ.jpg'),
    'แกงจืดสาหร่ายหมูสัป.jpeg': require('./แกงจืดสาหร่ายหมูสัป.jpeg'),
    'ชาเย็ย.jpg': require('./ชาเย็ย.jpg'),
    'ต้มจืดเต้าหู้หมูสับ.jpg': require('./ต้มจืดเต้าหู้หมูสับ.jpg'),
    'ต้มยำกุ้ง.jpg': require('./ต้มยำกุ้ง.jpg'),
    'ต้มยำไก่.jpg': require('./ต้มยำไก่.jpg'),
    'น้ำเปล่า.jpg': require('./น้ำเปล่า.jpg'),
    'น้ำอัดลม.jpg': require('./น้ำอัดลม.jpg'),
    'ผักสลัด.jpg': require('./ผักสลัด.jpg'),
    'ผัดซีอิ๋ว.jpg': require('./ผัดซีอิ๋ว.jpg'),
    'ผัดผักรวม.jpg': require('./ผัดผักรวม.jpg'),
    'ผัดผัดคะน้า.jpg': require('./ผัดผัดคะน้า.jpg'),
    'ผัดพริกแกงไก่.jpg': require('./ผัดพริกแกงไก่.jpg'),
    'มะนาว.png': require('./มะนาว.png'),
    'ยำทะเล.jpg': require('./ยำทะเล.jpg'),
    'ยำวุ้นเส้น.jpg': require('./ยำวุ้นเส้น.jpg'),
    'ยำหมูยอ.jpg': require('./ยำหมูยอ.jpg'),
    'สลัดไก่ย่าง.jpg': require('./สลัดไก่ย่าง.jpg'),
    'แกงเขียวหวานไก่.jpeg': require('./แกงเขียวหวานไก่.jpeg'),
    'ข้าวมันไก่.jpg': require('./ข้าวมันไก่.jpg'),
    'หมูกระเทียม.jpg': require('./หมูกระเทียม.jpg'),
};

export const AddPic = (name) => images[name] || null;