import { StyleSheet } from 'react-native';
import { colors } from './theme';

export const styles = StyleSheet.create({
    foodRoot: {
        flex: 1,
        backgroundColor: colors.bg,
    },
    foodHeader: {
        height: 70,
        paddingHorizontal: 30,
        backgroundColor: colors.surface,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    foodHeaderTitle: {
        color: colors.white,
        fontSize: 24,
        fontWeight: '700',
    },
    backButton: {
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderRadius: 8,
        backgroundColor: colors.primaryLight,
    },
    backButtonText: {
        color: colors.primary,
        fontSize: 16,
        fontWeight: '600',
    },
    foodContent: {
        flex: 1,
        flexDirection: 'row',
    },
    categorySidebar: {
        width: 220,
        padding: 20,
        backgroundColor: colors.surface,
        borderRightWidth: 1,
        borderRightColor: colors.border,
    },
    categoryTitle: {
        color: colors.text1,
        fontSize: 20,
        fontWeight: '700',
        marginBottom: 15,
    },
    categoryButton: {
        minHeight: 52,
        paddingHorizontal: 15,
        marginBottom: 8,
        borderRadius: 10,
        justifyContent: 'center',
    },
    categoryButtonActive: {
        backgroundColor: colors.primaryLight,
    },
    categoryText: {
        color: colors.text2,
        fontSize: 16,
        fontWeight: '500',
    },
    categoryTextActive: {
        color: colors.primary,
        fontWeight: '700',
    },
    foodListContainer: {
        flex: 1,
        paddingHorizontal: 25,
        paddingTop: 20,
    },
    foodListTitle: {
        color: colors.text1,
        fontSize: 22,
        fontWeight: '700',
        marginBottom: 15,
    },
    foodList: {
        paddingBottom: 25,
    },
    foodRow: {
        gap: 16,
        marginBottom: 16,
    },
    foodCard: {
        width: '23.7%',
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: 12,
        overflow: 'hidden',
        elevation: 2,
    },
    foodImage: {
        width: '100%',
        height: 130,
        resizeMode: 'cover',
        backgroundColor: colors.disabled,
    },
    foodImagePlaceholder: {
        width: '100%',
        height: 130,
        backgroundColor: colors.disabled,
        justifyContent: 'center',
        alignItems: 'center',
    },
    foodImagePlaceholderText: {
        color: colors.disabledText,
        fontSize: 14,
    },
    foodInfo: {
        padding: 12, 
        position: 'relative', 
    },
    foodName: {
        color: colors.text1,
        fontSize: 17,
        fontWeight: '600',
        minHeight: 42,
    },
    foodPrice: {
        color: colors.primary,
        fontSize: 17,
        fontWeight: '700',
        marginTop: 5,
    },
        cartButton: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: 8,
            paddingHorizontal: 18,
            paddingVertical: 10,
            borderRadius: 8,
            backgroundColor: colors.white,
            marginRight: 10,
        },
        cartButtonText: {
            color: colors.primary,
            fontSize: 16,
            fontWeight: '600',
        },
        cartBadge: {
            minWidth: 20,
            height: 20,
            borderRadius: 10,
            paddingHorizontal: 5,
            backgroundColor: colors.red,
            alignItems: 'center',
            justifyContent: 'center',
        },
        cartBadgeText: {
            color: colors.white,
            fontSize: 11,
            fontWeight: '700',
        },
        headerRight: {
            flexDirection: 'row',
            alignItems: 'center',
        },
            floatingCart: {
        position: 'absolute',
        left: 20,
        bottom: 30,
        minHeight: 52,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        borderRadius: 10,
        backgroundColor: colors.primary,
        elevation: 6,
    },
    cartButtonText: {
        color: colors.white,
        fontSize: 16,
        fontWeight: '700',
    },
    cartBadge: {
        minWidth: 24,
        height: 24,
        marginLeft: 10,
        borderRadius: 12,
        paddingHorizontal: 6,
        backgroundColor: colors.white,
        alignItems: 'center',
        justifyContent: 'center',
    },
    cartBadgeText: {
        color: colors.primary,
        fontSize: 13,
        fontWeight: '700',
    },
    addFoodButton: {
    position: 'absolute',
    right: 8,
    bottom: 8,
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    elevation: 3,
},
addFoodButtonText: {
    color: colors.white,
    fontSize: 20,
    fontWeight: '700',
    lineHeight: 22,
},
});